################################################################################
#
#   Calculates the Hamming Distance between the final generated image and the
#   a sample edge set calculated using cv2. Each bit is compared one by one. 
#   Every time two bits do not match, 1 is added to the fitness. A lower fitness
#   is better.
#
#   Parameters:
#   initial_image - the image generated by initialize_population
#   final_image - the result of applying the rules on the initial_image
#
#   Returns:
#   an integer corresponding to the number of bit
#
################################################################################

import cv2
import numpy as np

def calculate_fitness(start_image, final_image):
  #edges = cv2.Canny(start_image, 256, 256)
  # fitness = 0

  # for x_pixel in range(len(start_image)):
  #   for y_pixel in range(len(start_image)):
  #     if final_image[x_pixel][y_pixel] != start_image[x_pixel][y_pixel]:
  #       fitness = fitness + 1

  return np.sum(np.sum(np.bitwise_xor(start_image, final_image)))  